// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hardware_encoding_Block_split28_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        compress_size_0_dout,
        compress_size_0_empty_n,
        compress_size_0_read,
        lzw_size_dout,
        lzw_size_empty_n,
        lzw_size_read,
        m_axi_HP0_AWVALID,
        m_axi_HP0_AWREADY,
        m_axi_HP0_AWADDR,
        m_axi_HP0_AWID,
        m_axi_HP0_AWLEN,
        m_axi_HP0_AWSIZE,
        m_axi_HP0_AWBURST,
        m_axi_HP0_AWLOCK,
        m_axi_HP0_AWCACHE,
        m_axi_HP0_AWPROT,
        m_axi_HP0_AWQOS,
        m_axi_HP0_AWREGION,
        m_axi_HP0_AWUSER,
        m_axi_HP0_WVALID,
        m_axi_HP0_WREADY,
        m_axi_HP0_WDATA,
        m_axi_HP0_WSTRB,
        m_axi_HP0_WLAST,
        m_axi_HP0_WID,
        m_axi_HP0_WUSER,
        m_axi_HP0_ARVALID,
        m_axi_HP0_ARREADY,
        m_axi_HP0_ARADDR,
        m_axi_HP0_ARID,
        m_axi_HP0_ARLEN,
        m_axi_HP0_ARSIZE,
        m_axi_HP0_ARBURST,
        m_axi_HP0_ARLOCK,
        m_axi_HP0_ARCACHE,
        m_axi_HP0_ARPROT,
        m_axi_HP0_ARQOS,
        m_axi_HP0_ARREGION,
        m_axi_HP0_ARUSER,
        m_axi_HP0_RVALID,
        m_axi_HP0_RREADY,
        m_axi_HP0_RDATA,
        m_axi_HP0_RLAST,
        m_axi_HP0_RID,
        m_axi_HP0_RUSER,
        m_axi_HP0_RRESP,
        m_axi_HP0_BVALID,
        m_axi_HP0_BREADY,
        m_axi_HP0_BRESP,
        m_axi_HP0_BID,
        m_axi_HP0_BUSER
);

parameter    ap_ST_fsm_state1 = 71'd1;
parameter    ap_ST_fsm_state2 = 71'd2;
parameter    ap_ST_fsm_state3 = 71'd4;
parameter    ap_ST_fsm_state4 = 71'd8;
parameter    ap_ST_fsm_state5 = 71'd16;
parameter    ap_ST_fsm_state6 = 71'd32;
parameter    ap_ST_fsm_state7 = 71'd64;
parameter    ap_ST_fsm_state8 = 71'd128;
parameter    ap_ST_fsm_state9 = 71'd256;
parameter    ap_ST_fsm_state10 = 71'd512;
parameter    ap_ST_fsm_state11 = 71'd1024;
parameter    ap_ST_fsm_state12 = 71'd2048;
parameter    ap_ST_fsm_state13 = 71'd4096;
parameter    ap_ST_fsm_state14 = 71'd8192;
parameter    ap_ST_fsm_state15 = 71'd16384;
parameter    ap_ST_fsm_state16 = 71'd32768;
parameter    ap_ST_fsm_state17 = 71'd65536;
parameter    ap_ST_fsm_state18 = 71'd131072;
parameter    ap_ST_fsm_state19 = 71'd262144;
parameter    ap_ST_fsm_state20 = 71'd524288;
parameter    ap_ST_fsm_state21 = 71'd1048576;
parameter    ap_ST_fsm_state22 = 71'd2097152;
parameter    ap_ST_fsm_state23 = 71'd4194304;
parameter    ap_ST_fsm_state24 = 71'd8388608;
parameter    ap_ST_fsm_state25 = 71'd16777216;
parameter    ap_ST_fsm_state26 = 71'd33554432;
parameter    ap_ST_fsm_state27 = 71'd67108864;
parameter    ap_ST_fsm_state28 = 71'd134217728;
parameter    ap_ST_fsm_state29 = 71'd268435456;
parameter    ap_ST_fsm_state30 = 71'd536870912;
parameter    ap_ST_fsm_state31 = 71'd1073741824;
parameter    ap_ST_fsm_state32 = 71'd2147483648;
parameter    ap_ST_fsm_state33 = 71'd4294967296;
parameter    ap_ST_fsm_state34 = 71'd8589934592;
parameter    ap_ST_fsm_state35 = 71'd17179869184;
parameter    ap_ST_fsm_state36 = 71'd34359738368;
parameter    ap_ST_fsm_state37 = 71'd68719476736;
parameter    ap_ST_fsm_state38 = 71'd137438953472;
parameter    ap_ST_fsm_state39 = 71'd274877906944;
parameter    ap_ST_fsm_state40 = 71'd549755813888;
parameter    ap_ST_fsm_state41 = 71'd1099511627776;
parameter    ap_ST_fsm_state42 = 71'd2199023255552;
parameter    ap_ST_fsm_state43 = 71'd4398046511104;
parameter    ap_ST_fsm_state44 = 71'd8796093022208;
parameter    ap_ST_fsm_state45 = 71'd17592186044416;
parameter    ap_ST_fsm_state46 = 71'd35184372088832;
parameter    ap_ST_fsm_state47 = 71'd70368744177664;
parameter    ap_ST_fsm_state48 = 71'd140737488355328;
parameter    ap_ST_fsm_state49 = 71'd281474976710656;
parameter    ap_ST_fsm_state50 = 71'd562949953421312;
parameter    ap_ST_fsm_state51 = 71'd1125899906842624;
parameter    ap_ST_fsm_state52 = 71'd2251799813685248;
parameter    ap_ST_fsm_state53 = 71'd4503599627370496;
parameter    ap_ST_fsm_state54 = 71'd9007199254740992;
parameter    ap_ST_fsm_state55 = 71'd18014398509481984;
parameter    ap_ST_fsm_state56 = 71'd36028797018963968;
parameter    ap_ST_fsm_state57 = 71'd72057594037927936;
parameter    ap_ST_fsm_state58 = 71'd144115188075855872;
parameter    ap_ST_fsm_state59 = 71'd288230376151711744;
parameter    ap_ST_fsm_state60 = 71'd576460752303423488;
parameter    ap_ST_fsm_state61 = 71'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 71'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 71'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 71'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 71'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 71'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 71'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 71'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 71'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 71'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 71'd1180591620717411303424;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] compress_size_0_dout;
input   compress_size_0_empty_n;
output   compress_size_0_read;
input  [63:0] lzw_size_dout;
input   lzw_size_empty_n;
output   lzw_size_read;
output   m_axi_HP0_AWVALID;
input   m_axi_HP0_AWREADY;
output  [63:0] m_axi_HP0_AWADDR;
output  [0:0] m_axi_HP0_AWID;
output  [31:0] m_axi_HP0_AWLEN;
output  [2:0] m_axi_HP0_AWSIZE;
output  [1:0] m_axi_HP0_AWBURST;
output  [1:0] m_axi_HP0_AWLOCK;
output  [3:0] m_axi_HP0_AWCACHE;
output  [2:0] m_axi_HP0_AWPROT;
output  [3:0] m_axi_HP0_AWQOS;
output  [3:0] m_axi_HP0_AWREGION;
output  [0:0] m_axi_HP0_AWUSER;
output   m_axi_HP0_WVALID;
input   m_axi_HP0_WREADY;
output  [31:0] m_axi_HP0_WDATA;
output  [3:0] m_axi_HP0_WSTRB;
output   m_axi_HP0_WLAST;
output  [0:0] m_axi_HP0_WID;
output  [0:0] m_axi_HP0_WUSER;
output   m_axi_HP0_ARVALID;
input   m_axi_HP0_ARREADY;
output  [63:0] m_axi_HP0_ARADDR;
output  [0:0] m_axi_HP0_ARID;
output  [31:0] m_axi_HP0_ARLEN;
output  [2:0] m_axi_HP0_ARSIZE;
output  [1:0] m_axi_HP0_ARBURST;
output  [1:0] m_axi_HP0_ARLOCK;
output  [3:0] m_axi_HP0_ARCACHE;
output  [2:0] m_axi_HP0_ARPROT;
output  [3:0] m_axi_HP0_ARQOS;
output  [3:0] m_axi_HP0_ARREGION;
output  [0:0] m_axi_HP0_ARUSER;
input   m_axi_HP0_RVALID;
output   m_axi_HP0_RREADY;
input  [31:0] m_axi_HP0_RDATA;
input   m_axi_HP0_RLAST;
input  [0:0] m_axi_HP0_RID;
input  [0:0] m_axi_HP0_RUSER;
input  [1:0] m_axi_HP0_RRESP;
input   m_axi_HP0_BVALID;
output   m_axi_HP0_BREADY;
input  [1:0] m_axi_HP0_BRESP;
input  [0:0] m_axi_HP0_BID;
input  [0:0] m_axi_HP0_BUSER;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg compress_size_0_read;
reg lzw_size_read;
reg m_axi_HP0_AWVALID;
reg m_axi_HP0_WVALID;
reg m_axi_HP0_BREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [70:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    compress_size_0_blk_n;
reg    lzw_size_blk_n;
reg    HP0_blk_n_AW;
wire    ap_CS_fsm_state2;
reg    HP0_blk_n_W;
wire    ap_CS_fsm_state3;
reg    HP0_blk_n_B;
wire    ap_CS_fsm_state71;
reg   [31:0] compress_size_0_read_reg_96;
reg   [63:0] HP0_addr_reg_101;
wire  signed [63:0] sext_ln302_fu_86_p1;
reg    ap_block_state1;
wire   [61:0] trunc_ln_fu_76_p4;
reg   [70:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 71'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state71) & (m_axi_HP0_BVALID == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        HP0_addr_reg_101 <= sext_ln302_fu_86_p1;
        compress_size_0_read_reg_96 <= compress_size_0_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        HP0_blk_n_AW = m_axi_HP0_AWREADY;
    end else begin
        HP0_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state71)) begin
        HP0_blk_n_B = m_axi_HP0_BVALID;
    end else begin
        HP0_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        HP0_blk_n_W = m_axi_HP0_WREADY;
    end else begin
        HP0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state71) & (m_axi_HP0_BVALID == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state71) & (m_axi_HP0_BVALID == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        compress_size_0_blk_n = compress_size_0_empty_n;
    end else begin
        compress_size_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((lzw_size_empty_n == 1'b0) | (compress_size_0_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        compress_size_0_read = 1'b1;
    end else begin
        compress_size_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        lzw_size_blk_n = lzw_size_empty_n;
    end else begin
        lzw_size_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((lzw_size_empty_n == 1'b0) | (compress_size_0_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        lzw_size_read = 1'b1;
    end else begin
        lzw_size_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (m_axi_HP0_AWREADY == 1'b1))) begin
        m_axi_HP0_AWVALID = 1'b1;
    end else begin
        m_axi_HP0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state71) & (m_axi_HP0_BVALID == 1'b1))) begin
        m_axi_HP0_BREADY = 1'b1;
    end else begin
        m_axi_HP0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (m_axi_HP0_WREADY == 1'b1))) begin
        m_axi_HP0_WVALID = 1'b1;
    end else begin
        m_axi_HP0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((lzw_size_empty_n == 1'b0) | (compress_size_0_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (m_axi_HP0_AWREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (m_axi_HP0_WREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            if (((1'b1 == ap_CS_fsm_state71) & (m_axi_HP0_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state71;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

always @ (*) begin
    ap_block_state1 = ((lzw_size_empty_n == 1'b0) | (compress_size_0_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign m_axi_HP0_ARADDR = 64'd0;

assign m_axi_HP0_ARBURST = 2'd0;

assign m_axi_HP0_ARCACHE = 4'd0;

assign m_axi_HP0_ARID = 1'd0;

assign m_axi_HP0_ARLEN = 32'd0;

assign m_axi_HP0_ARLOCK = 2'd0;

assign m_axi_HP0_ARPROT = 3'd0;

assign m_axi_HP0_ARQOS = 4'd0;

assign m_axi_HP0_ARREGION = 4'd0;

assign m_axi_HP0_ARSIZE = 3'd0;

assign m_axi_HP0_ARUSER = 1'd0;

assign m_axi_HP0_ARVALID = 1'b0;

assign m_axi_HP0_AWADDR = HP0_addr_reg_101;

assign m_axi_HP0_AWBURST = 2'd0;

assign m_axi_HP0_AWCACHE = 4'd0;

assign m_axi_HP0_AWID = 1'd0;

assign m_axi_HP0_AWLEN = 32'd1;

assign m_axi_HP0_AWLOCK = 2'd0;

assign m_axi_HP0_AWPROT = 3'd0;

assign m_axi_HP0_AWQOS = 4'd0;

assign m_axi_HP0_AWREGION = 4'd0;

assign m_axi_HP0_AWSIZE = 3'd0;

assign m_axi_HP0_AWUSER = 1'd0;

assign m_axi_HP0_RREADY = 1'b0;

assign m_axi_HP0_WDATA = compress_size_0_read_reg_96;

assign m_axi_HP0_WID = 1'd0;

assign m_axi_HP0_WLAST = 1'b0;

assign m_axi_HP0_WSTRB = 4'd15;

assign m_axi_HP0_WUSER = 1'd0;

assign sext_ln302_fu_86_p1 = $signed(trunc_ln_fu_76_p4);

assign trunc_ln_fu_76_p4 = {{lzw_size_dout[63:2]}};

endmodule //hardware_encoding_Block_split28_proc
